version: "3.8"
services:
    client:
        build: ./client
        container_name: obitasks-react-client
        ports:
            - "3000:3000"
        volumes:
            - ./client:/app
            - /app/node_modules
        stdin_open: true
        tty: true
    server:
        build: ./server
        image: obitasks-server
        container_name: obitasks-node-server
        ports:
          - "5000:5000"
        volumes:
            - ./server:/app
            - /app/node_modules/
        depends_on:
            - mongo
        env_file: ./server/.env