version: "3.8"
services:
    client:
        build: ./client
        container_name: obitasks-react-client
        ports:
            - "3000:3000"
        volumes:
            - ./client:/app
            - /app/node_modules
        depends_on:
            - server
        networks:
            - app-network
        stdin_open: true
        tty: true
    server:
        build: ./server
        image: obitasks-server
        container_name: obitasks-node-server
        ports:
          - "5000:5000"
        volumes:
            - ./server:/app
            - /app/node_modules/
        depends_on:
            - mongo
        env_file: ./server/.env
        environment:
            - NODE_ENV=production
        networks:
            - app-network
    mongo:
        image: mongo
        volumes:
            - data-volume:/data/db
        ports:
            - "27017:27017"
        networks:
            - app-network
networks:
  app-network:

volumes:
    data-volume:
    node_modules:
    web-root:
        driver: local